### ISSUE TITLE
Can’t get replicate your config

### ISSUE THREAD

**Issue by xeijin** [fuxialexander/doom-emacs-private-xfu#1]
Hello,

Your config looks quite interesting to me, unfortunately following the instructions in the README to replicate your setup does not work for me, it seems the doom-theme you use plus several other plugins do not load.

I’ve tried the following remedies:

- switching to the ‘develop’ branch of doom-emacs
- fixing the absolute reference (which currently references your home dir) to your init.emacs.el in the alias ‘init.el’ 

I am using macOS High Sierra. Any ideas?

**Comment by fuxialexander** [comment]
you need to check out the submodule which contains the theme

https://github.com/fuxialexander/doom-emacs-private-xfu/blob/master/.gitmodules

also ensure you are on the lastest commit of doom-emacs develop branch

If you still have error, you can post the error message below.

**Comment by fuxialexander** [comment]
@xeijin I've updated the install instruction. Maybe you can have another try based on that.

**Comment by xeijin** [comment]
Thank you, will try as soon as I get a chance.

**Comment by xeijin** [comment]
Thanks for the updated instructions, I got this working. Here were my high-level steps for anyone doing it from scratch on macOS:

- `rm -rf` on `~/.emacs.d` and `~/.doom.d` to remove any existing directories
- copied and pasted in the updated install instructions from your README
- When running `cd ~/.emacs.d && make` I got an error about `init.el` not existing in `~/.doom.d`
- I fixed that by running `rm -rf init.el` and `ln -s ./init.mac.el init.el` in `~/.doom.d`
- Then it finally worked (with a couple of MELPA errors) after running `cd ~/.emacs.d && make` again

I am finding I don't have quite a few of the required fonts here-and-there, do you have a list of these anywhere?

**Comment by fuxialexander** [comment]
@xeijin 

- SF Mono
- SF Compact/UI Display 
- Iosevka
- Sarasa Mono SC

**Comment by xeijin** [comment]
@fuxialexander looks like the instructions on the install page have changed, and I can no longer init the submodule per old instructions, did something change?

**Comment by fuxialexander** [comment]
The submodule is not needed anymore. You can simply follow the new instruction.

**Comment by xeijin** [comment]
I did follow the instructions, but when I load emacs it says fo packages
are loaded successfully but I don’t see any of the key UI tweaks, and a
bunch of things seem to be missing e.g ivy/counsel and space / leader to
bring up the menu.

This is via Windows Subsystem for Linux, so will try on my MacBook later
and report back, though ‘vanilla’ doom worked fine on the same setup.

**Comment by xeijin** [comment]
No didn't work on macOs either unfortunately, here is what I'm presented with (missing your theme, also seems like no completion framework loaded?)

![image](https://user-images.githubusercontent.com/291385/43001193-3c2fbd12-8c1c-11e8-8fa7-ecaf96f783af.png)

**Comment by xeijin** [comment]
@fuxialexander any idea what's going on?

**Comment by fuxialexander** [comment]
@xeijin Sorry...no idea on that... Actually I just setup the config on another mac without problem...

**Comment by xeijin** [comment]
Got it working -- I had to rename `init.mac.el` to `init.el` inside `.doom.d`.

**Comment by fuxialexander** [comment]
@xeijin actually I softlink it to init.el to avoid git problem
