### ISSUE TITLE
make 时候出现一点问题

### ISSUE THREAD

**Issue by flying-ming** [fuxialexander/doom-emacs-private-xfu#2]
首先 我按照README中的步骤 替换了 ~/.doom, 然后重命名 init.mac.el 为 init.el。最后 make。包按照完后，出现下列文字，我全部都选的n。结果make不动了。求教 是特别慢还是bug？

`
Loading /Users/xfu/Dropbox/org/ref.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/_idea.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Error running timer ‘org-clock-save’: (file-missing "Opening output file" "No such file or directory" "/Users/gaoming/org/.org-clock-persist-data.el")
Loading /Users/xfu/Dropbox/org/_inbox.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/_workflow.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Updating mails...
Loading /Users/xfu/Dropbox/org/_learn.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/_review.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/_meeting.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/_life.org
Directory `/Users/xfu/Dropbox/org/' does not exist! Create it? (y or n) n
File mode specification error: (file-missing Setting current directory No such file or directory /Users/xfu/Dropbox/org/)
Loading /Users/xfu/Dropbox/org/reference/Bibliography.bib
Directory `/Users/xfu/Dropbox/org/reference/' does not exist! Create it? (y or n) n
Error running timer ‘org-clock-save’: (file-missing "Opening output file" "No such file or directory" "/Users/gaoming/org/.org-clock-persist-data.el")
Updating mails...
Error running timer ‘org-clock-save’: (file-missing "Opening output file" "No such file or directory" "/Users/gaoming/org/.org-clock-persist-data.el")
Updating mails...
`

**Comment by fuxialexander** [comment]
之前我的code里有不少hardcode的path 现在应该没这个问题了
