### ISSUE TITLE
do-repeat! issues

### ISSUE THREAD

**Issue by alienzj** [fuxialexander/doom-emacs-private-xfu#3]
![图片](https://user-images.githubusercontent.com/8847420/57571337-491e6080-743f-11e9-83e1-50a81a38117c.png)
Hello, fuxi,
I use this [config](https://github.com/alienzj/doom-emacs-private-zj) (fork of your doom-emacs-private-xfu)
But have **void-function do-repeat!** problem.
Could you help me?
Thanks very much!

**Comment by fuxialexander** [comment]
Please `git pull --rebase`, I've just pushed my local commits and it should be OK now.

**Comment by fuxialexander** [comment]
Ah, seems you are using your own fork. You can delete all `do-repeat!` entries in the file `+bindings.el`, which should solve this problem. The upstream `doom-emacs` has removed this function.

**Comment by alienzj** [comment]
OK, I will diff it, and change it.
Thanks very much~
