### ISSUE TITLE
建议注释掉sh-mode的electric-operator

### ISSUE THREAD

**Issue by 3jQQuY** [fuxialexander/doom-emacs-private-xfu#4]
config.el:
:hook (
         ;; (sh-mode . electric-operator-mode)
         (ess-mode . electric-operator-mode)
         (python-mode . electric-operator-mode)))
感觉这个自动替换莫名加一些错误的空格(
话说大佬的配置文件用起来好舒服

**Comment by fuxialexander** [comment]
鸽了一段时间。。现在暂时把electric operator mode去掉了。。再研究一段时间再看要不要加回来
