### ISSUE TITLE
Compiler-macro error for +workspace-p: (invalid-read-syntax "] in a list")

### ISSUE THREAD

**Issue by p9s** [fuxialexander/doom-emacs-private-xfu#5]
Compiler-macro error for +workspace-p: (invalid-read-syntax "] in a list")
Failed to load ’org-faces’ package incrementally, because: (error Font not available #<font-spec nil nil Iosevka nil nil nil nil nil nil nil nil nil ((:name . Iosevka) (:user-spec . Iosevka))>)
Failed to load ’org’ package incrementally, because: (error Font not available #<font-spec nil nil Iosevka nil nil nil nil nil nil nil nil nil ((:name . Iosevka) (:user-spec . Iosevka))>)
Failed to load ’org-agenda’ package incrementally, because: (error Font not available #<font-spec nil nil Iosevka nil nil nil nil nil nil nil nil nil ((:name . Iosevka) (:user-spec . Iosevka))>)
Failed to load ’org-capture’ package incrementally, because: (error Font not available #<font-spec nil nil Iosevka nil nil nil nil nil nil nil nil nil ((:name . Iosevka) (:user-spec . Iosevka))>)
Failed to load ’org’ package incrementally, because: (error Font not available #<font-spec nil nil Iosevka nil nil nil nil nil nil nil nil nil ((:name . Iosevka) (:user-spec . Iosevka))>)
<C-s-268632065> is undefined

**Comment by fuxialexander** [comment]
Install Iosevka font https://typeof.net/Iosevka/
