### ISSUE TITLE
popup-rule for *Password-Store* doesn't work

### ISSUE THREAD

**Issue by WhatDothLife** [fuxialexander/doom-emacs-private-xfu#6]
I copied some of your popup-rules from `+popup.el` since these are sane defaults. Unfortunately, the rule defined for the `*Password-Store*` buffer doesn't work. The buffer doesn't respond to `C-g`, and is displayed in the wrong size, as if there was no rule at all.

Are you experiencing any similar issues or can you guess what could be a reason for this strange behavior?

**Comment by fuxialexander** [comment]
I haven't used that rule for a long time...so sorry I'm not sure about that
